DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(

usrname		VARCHAR(50) NOT NULL,
passwrd		VARCHAR(50) NOT NULL,

PRIMARY KEY (usrname)

)ENGINE = INNODB;


DROP TABLE IF EXISTS IMAGE;
CREATE TABLE IMAGE
(

fname		VARCHAR(50) NOT NULL,
image 		BLOB NOT NULL,
edit		CHAR DEFAULT 'N',
uname		VARCHAR(50) NOT NULL,
otime		DATETIME DEFAULT CURRENT_TIMESTAMP,
etime		DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY (uname),
FOREIGN KEY (uname) REFERENCES USER (usrname)


) ENGINE =INNODB;

