CREATE DATABASE IF NOT EXISTS TOPAZ;

USE TOPAZ;

DROP TABLE IF EXISTS IMAGE;
DROP TABLE IF EXISTS USER;

CREATE TABLE USER
(

usrname		VARCHAR(50) NOT NULL,
passwrd		VARCHAR(50) NOT NULL,

PRIMARY KEY (usrname)

)ENGINE = INNODB;



CREATE TABLE IMAGE
(

fname		VARCHAR(50) NOT NULL,
image 		BLOB NOT NULL,
edit		CHAR DEFAULT 'N',
uname		VARCHAR(50) NOT NULL,
otime		DATETIME DEFAULT CURRENT_TIMESTAMP,
etime		DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY (uname, fname),
FOREIGN KEY (uname) REFERENCES USER (usrname)


) ENGINE =INNODB;

