CREATE TABLE IMAGE
(

fname		VARCHAAR(50) NOT NULL,
image 		BLOB NOT NULL,
edit		CHAR DEFAULT 'N',
uname		VARCHAAR(50) NOT NULL,
otime		DATETIME DEFAULT CURRENT_TIMESTAMP,
etime		DATETIME DEFAULT ON UPDATE CURRENT_TIMESTAMP,

PRIMARY KEY (uname),
FOREIGN KEY (uname) REFERENCES USER (usrname)


) ENGINE =INNODB;

CREATE TABLE USER
(

usrname		VARCHAAR(50) NOT NULL,
passwrd		VARCHAR(50) NOT NULL,

PRIMARY KEY (usrname)

)ENGINE = INNODB;